### ISSUE TITLE
[EPIC] RHODS 1.34: Dev Tracker

### ISSUE THREAD

**Issue by heyselbi** [red-hat-data-services/odh-model-controller#12]
**Issues that are targeted for 1.34:**

_ModelMesh:_
- [ ] Text

_KServe/Caikit/TGIS:_
- [ ] Text

**Comment by ldimaggi** [comment]
Does the fact that this issue is empty indicate that there are zero new features for model serving for 1.34? Thx!

**Comment by heyselbi** [comment]
Hi @ldimaggi , I will update it before the end of this week. 

But I created this before being aware of Deepak's script that retrieves all the issues directly from commits to red-hat-data-services. So, if that script stays, we will probably resort to those JIRAs for a list of issues for the next RHODS releases.

**Comment by heyselbi** [comment]
Deepak's script will be taking care of it.
